#  _   _                  _                 _ 
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|                             
#  ____        _    __ _ _           
# |  _ \  ___ | |_ / _(_) | ___  ___ 
# | | | |/ _ \| __| |_| | |/ _ \/ __|
# | |_| | (_) | |_|  _| | |  __/\__ \
# |____/ \___/ \__|_| |_|_|\___||___/
# 
# SBDots
# By: Saifullah Balghari


# Configurations
source = $HOME/.config/hypr/hyprland/animation.conf
source = $HOME/.config/hypr/hyprland/decoration.conf
source = $HOME/.config/hypr/hyprland/enviromentvars.conf
source = $HOME/.config/hypr/hyprland/general.conf
source = $HOME/.config/hypr/hyprland/input.conf
source = $HOME/.config/hypr/hyprland/keybindings.conf
source = $HOME/.config/hypr/hyprland/misc.conf
source = $HOME/.config/hypr/hyprland/monitor.conf
source = $HOME/.config/hypr/hyprland/windowrules.conf

# Startup Apps & Services
exec-once = sbdotsctl waybar start
exec-once = systemctl --user start --now hyprpolkitagent
exec-once = systemctl --user start --now sbdots-actionsd.service
exec-once = systemctl --user start --now sbdots-clipboard-listenerd.service
exec-once = systemctl --user start --now swaync.service
exec-once = wl-paste --watch &
exec-once = udiskie &
exec-once = devify &
exec-once = waypaper --restore &
