# Applets
windowrule {
  name = windowrule-1
  float = on
  size = (monitor_w*0.4) (monitor_h*0.5)
  match:class = (blueman-manager)
}

windowrule {
  name = windowrule-2
  float = on
  size = (monitor_w*0.6) (monitor_h*0.5)
  match:class = (org.pulseaudio.pavucontrol)
}


# Applications (i prefer them as floating) 
windowrule {
  name = windowrule-3
  float = on
  center = 1
  size = (monitor_w*0.6) (monitor_h*0.6)
  match:title = (Warehouse)|(nwg_look)|(Ark)|(Qt5 Configuration Tool)|(Qt6 Configuration Tool)|(Flatseal)|(Kvantum Manager)|(VLC media player)|(Sign in – Google accounts — Mozilla Firefox)
}


# Waypaper: Wallpaper manager
windowrule {
  name = windowrule-4
  float = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  match:title = ^(.*Waypaper.*)$
}

windowrule {
  name = windowrule-5
  center = 1
  match:title = ^(.*Waypaper.*)$1
}


## Specific applications
windowrule {
  name = windowrule-6
  float = on
  center = 1
  size = (monitor_w*0.62) (monitor_h*0.62)
  match:class = (org.gnome.Loupe)|(io.missioncenter.MissionCenter)|(org.kde.dolphin)|(org.gnome.Nautilus)|(vlc)|(com.github.th_ch.youtube_music)|(org.gnome.TextEditor)
}


# Smile (emoji picker)
windowrule {
  name = windowrule-7
  float = on
  pin = on
  move = ((monitor_w*1)-window_w-10) (50)
  match:class = (it.mijorus.smile)
}


# File dialogs 

# General floating
windowrule {
  name = windowrule-8
  float = on
  size = (monitor_w*0.6) (monitor_h*0.6)
  match:title = (Open Folder)|(Open File)|(Save File)|(Save Folder)|(Save Image)|(Save As)|(Open As)|(Select file)|(Select folder)|(Open Archive)
}

